title: CruftyOldSysadmin, the life and times of a Nomadic Devops Engineer named Michael.
theme: jekyll-theme-tactile
email: cruftyold@gmail.com
description: >
  The ramblings of a nomadic systems administrator / devops engineer roaming the world seeking adventure, gainful employment, and percussion.
url: "http://cruftyoldsysadmin.github.io"
github_username: cruftyoldsysadmin
