title: CruftyOldSysadmin, the life and times of a Nomadic Devops Engineer named Michael.
theme: minima
email: cruftyold@gmail.com
description: >
  The ramblings of a nomadic systems administrator / devops engineer roaming the world seeking adventure, gainful employment, and percussion.
baseurl: "cruftyoldsysadmin.github.io"
github_username: cruftyoldsysadmin
