title: Life and times of a Nomadic Devops Engineer named Michael.
theme: jekyll-theme-tactile
email: cruftyold@gmail.com
description: >
  The ramblings of a nomadic systems administrator / devops engineer roaming the world seeking adventure, gainful employment, and percussion.
github_username: cruftyoldsysadmin
linkedin: nomadicengineer
social-network-links:
  rss: true
  linkedin: nomadicengineer
  timezone: "Asia/Istanbul"
  paginate: 5
  
