title: CruftyOldSysadmin, the life and times of a Nomadic Devops Engineer named Michael.
theme: jekyll-theme-tactile
email: cruftyold@gmail.com
description: >
  Greetings! As you might guess, I'm a crufty old systems administrator.  For the purpose of buzz-words, I'll call myself a "DevOps Engineer".
  Yes, I know your response is going to be getting indignant and yelling, "DevOps is not a title, it's a methodology!!". You're right, but my
  career focus in 2018 is implementing "DevOps methodologies" for my customers and employers, which is as much about social engineering as it is
  about software engineering. That's the last I'll entertain any discussion on the subject, if you have a problem with that, talk to the hand.

  I'm from San Francisco where I worked and consulted for many start-ups over the past 20 years, as well as several established companies.  My
  career has included shoveling chicken shit, bailing hay, tech support, hardware technician (building beowulf clusters from components and my 
  fingers have the scars to prove it), working myself half to death for start-ups (suchas sleeping under my desk with pneumonia while being 
  Napster's only systems administrator), running my own software companies (into the ground with some like popupradio.com, InstantLinux), running
  consulting companies (Halligan Infrastructure Designs and BitPusher, which I sold out of in 2010), playing music in San Francisco, and the street 
  while backpacking throughout Europe. 

  Currently I'm unemployed and seeking either 100% full-time employment with an American technology company,  or remote consulting/contracting for
  software companies anywhere.  I live in Istanbul (UTC+03:00), and am not interested in relocating to wherever it is your companiy is located. I really
  enjoy the freedom of a "Digital Nomad" lifestyle. Today I might be working from a 300-year old hookah lounge in Sultan Ahmet, tomorrow I could be
  in the Balkans working from a  mountain cabin, and the following week I might be in a Parisian cafe drinking far too much coffee and staring at my computer.
  
  Music is my true love.

url: "" # http://cruftyoldsysadmin.github.io
github_username: cruftyoldsysadmin
